### ISSUE TITLE
Update lesson state on client

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#138]
Currently you have to refresh the page to see lesson state update (like when lesson state progression buttons are used or lesson is proposed); should do this on the client for immediate feedback.

**Comment by joelhooks** [comment]
Is this either "pass the football" with a callback or introducing some existing state management/change observation solution?

Callback works for right now with like a "request reload callback".

Mobx looks very sane and low impact (versus like full blown redux) if we wanted to go full ham.

**Comment by trevordmiller** [comment]
@joelhooks I'm thinking to have `Request` handle this automatically; not sure of implementation details yet but along with the polling option, would be good to have the `data` sent back from request update on the client when the `request` is used.

**Comment by trevordmiller** [comment]
Mobx or something is also an option. I'll do some research when I get to this story and we can discuss more.

**Comment by joelhooks** [comment]
My concern would be that Request goes from this delightfully simple tool to a MobX/Redux/Whatever that we have to maintain. 

Mostly because these tools exists and have been well vetted in production. It's a hard async problem with lots of dark crevices.

`Request` manually reloading  it's request via callback would be excellent, and I don't think it goes too far up the slippery slope.

Should note that I need this now and we don't have to wait for you to get to it to make progress :)

**Comment by joelhooks** [comment]
I'm gonna spike a little preview PR with Mobx just to see what it looks like, I've only had a cursory introduction, but people sure rave about its simple solution to these issues.

**Comment by trevordmiller** [comment]
Moving to https://github.com/eggheadio/egghead-instructor-center/issues/138
